spring.application.name=hospital-admission

# Server Configuration
server.port=${PORT:8080}

# PostgreSQL Database Connection
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hospital_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rajaji.gh@gmail.com
spring.mail.password=mfxn entm vcfz gzcm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
